### ISSUE TITLE
seems this gloves plugin lag my server

### ISSUE THREAD

**Issue by nguyenbaodanh** [kaganus/gloves#3]
seems this gloves plugin lag my server,sv and var going high turned red
remove plugin server back to normal, any1 got the same problem ?

**Comment by Shaneajm** [comment]
Never had an issue with this. It could be because of the database connection being made locally but even then I don't think that would affect SV that much.

**Comment by kaganus** [comment]
i am using this plugins together with my ws plugin on a lot of servers, none of them goes over 0.005 ms variance
