### ISSUE TITLE
Gloves Glitch Fix

### ISSUE THREAD

**Issue by Waky-mKy** [kaganus/gloves#4]
This fixxes the glitching gloves.
Gloves_SetArmsModel(client,DEFAULT_ARMS_CT);
SetEntityModel(client,PATHS[iSkinNumCT[client]]);

Maybe you can add a native to set Default-Arms.

Regards Waky

**Comment by kaganus** [comment]
this is already mentioned since the release. if you want to avoid having gloves/arms bugs, you have to use the natives provided in the plugin thats changing the player and/or arm model.

the code you posted is literally what was supposed to be done in the first place
