### ISSUE TITLE
add a timer

### ISSUE THREAD

**Issue by Theedgeclan2** [kaganus/gloves#5]
i have defalt gloves that spawn on the players right away anyway to add a timer so 1 or 2 sec after join it gives them the gloves

**Comment by kaganus** [comment]
use the natives i provided with this plugin, in your other plugin when setting for gloves/arm models/custom player models. you dont need a timer for this. if you do this kind of stuff with a timer to override other plugins, you server will never be stable.

**Comment by Theedgeclan2** [comment]
do you do paid jobs? https://forums.alliedmods.net/showpost.php?p=2381554&postcount=134
